# Site settings
title: "Jay 'n Tash"
description: |
    Black Horse Brewery, Magaliesburg

    June 22, 2019
owner: Jay Wallder
first_published: 2018
email: asciicatdesigns@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.jayntash.moe." # the base hostname & protocol for your site

social:
  github: https://github.com/asciicat/wedding-site
  instagram: https://www.instagram.com/explore/tags/JayNTashWedding2019/

# Build settings
markdown: kramdown
